**Basic of Numpy** 

In [1]:
import numpy as np

In [ ]:
arr =np.array([1,2,3,4,5])# one dimensional array
print(arr)

[1 2 3 4 5]


In [3]:
print(arr.ndim)

1


In [4]:
print(arr.shape)

(5,)


In [5]:
print(arr.itemsize)

8


In [6]:
print(arr.dtype)

int64


In [ ]:
arr2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # two dimensional array
print(arr2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
print(arr2.ndim)

2


In [ ]:
#Numpy slicing
print(arr2[0:, 1]) #Selecting row by column meaning wer are selecting the first row which is indexed at 0 and 1 column from the second the row.

[2 9]


In [15]:
print(arr2[1,1])

9


In [17]:
print(arr2[0:, 3])

[ 4 11]


Basic Mathematics
* Addition (+)
* Multiplication (*)
* Subtraction (-)
* Division (/)
* Exponential (**)

In [19]:
Data = np.array([[1,2,3,4], [3,4,5,6]])
print(Data)

[[1 2 3 4]
 [3 4 5 6]]


In [20]:
print(Data + Data)

[[ 2  4  6  8]
 [ 6  8 10 12]]


In [21]:
Data*2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [22]:
Data**3

array([[  1,   8,  27,  64],
       [ 27,  64, 125, 216]])

In [23]:
Data/2

array([[0.5, 1. , 1.5, 2. ],
       [1.5, 2. , 2.5, 3. ]])